IF !DEF(_G_SPRITES)
_G_SPRITES SET "true"


RSRESET

SPRITE_CADENCE rb 4
SPRITE_HEART_FULL rb 4
SPRITE_HEART_HALF rb 4
SPRITE_HEART_EMPTY rb 4
SPRITE_SLIME_GREEN_0 rb 4
SPRITE_SLIME_BLUE_0 rb 4
SPRITE_SLIME_BLUE_1 rb 4
SPRITE_SLIME_YELLOW_0 rb 4
SPRITE_BAT_0 rb 4
SPRITE_BAT_RED_0 rb 4
SPRITE_SKELETON_0 rb 4
SPRITE_SKELETON_1 rb 4
SPRITE_SKELETON_YELLOW_0 rb 4
SPRITE_SKELETON_YELLOW_1 rb 4
SPRITE_SKELETON_YELLOW_HEADLESS rb 4
SPRITE_SKELETON_BLACK_0 rb 4
SPRITE_SKELETON_BLACK_1 rb 4
SPRITE_SKELETON_BLACK_HEADLESS rb 4
SPRITE_WRAITH_0 rb 4
SPRITE_DIREBAT_0 rb 4
SPRITE_DIREBAT_GREY_0 rb 4

ENDC
